/**
 * Idempotent SignalWire address provisioning for the HireWire login flow.
 *
 * Spec §SignalWire Provisioning:
 *  - `ensureWizardAgent`  -> onboarding webhook (wizard-agent name)
 *  - `ensureHireWireAgent` -> user-dialable address (hirewire-agent name)
 * Both have per-project Basic Auth (user/password generated by caller).
 *
 * Lifecycle:
 *   1. List resources, filter by name
 *   2. If exists w/ matching URL -> PATCH to rotate basic-auth creds
 *   3. If exists w/ different URL -> PATCH URL + creds
 *   4. If absent -> POST to create
 *
 * Throws `ProvisioningError` on any 4xx/5xx (login handler aborts the
 * transaction; no projects row is written).
 */

const TIMEOUT_MS = 10_000;
const MAX_RETRIES = 3;

export class ProvisioningError extends Error {
  constructor(public readonly status: number, message: string) {
    super(message);
  }
}

export interface ProvisioningInput {
  spaceUrl: string;
  signalwireProjectId: string;
  apiToken: string;
  appDomain: string;
  basicAuthUser: string;
  basicAuthPassword: string;
}

export interface ProvisioningResult {
  resourceId: string;
  action: 'created' | 'rotated' | 'patched';
}

function basicAuthHeader(projectId: string, apiToken: string): string {
  return 'Basic ' + Buffer.from(`${projectId}:${apiToken}`).toString('base64');
}

async function fetchWithRetry(
  url: string,
  init: RequestInit,
  attempt = 1,
): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const resp = await fetch(url, { ...init, signal: controller.signal });
    if (resp.status >= 500 && attempt < MAX_RETRIES) {
      const wait = 250 * 2 ** (attempt - 1);
      await new Promise((r) => setTimeout(r, wait));
      return fetchWithRetry(url, init, attempt + 1);
    }
    return resp;
  } catch (err) {
    if (attempt < MAX_RETRIES) {
      const wait = 250 * 2 ** (attempt - 1);
      await new Promise((r) => setTimeout(r, wait));
      return fetchWithRetry(url, init, attempt + 1);
    }
    throw new ProvisioningError(0, `network error: ${(err as Error).message}`);
  } finally {
    clearTimeout(timer);
  }
}

async function listResources(
  spaceUrl: string,
  authHeader: string,
  name: string,
): Promise<any[]> {
  const url = `https://${spaceUrl}/api/fabric/resources?name=${encodeURIComponent(name)}`;
  const resp = await fetchWithRetry(url, {
    method: 'GET',
    headers: { Authorization: authHeader, 'Content-Type': 'application/json' },
  });
  if (!resp.ok) {
    throw new ProvisioningError(resp.status, `list resources failed: ${await resp.text()}`);
  }
  const body = (await resp.json()) as { data?: any[] };
  return body.data ?? [];
}

async function patchResource(
  spaceUrl: string,
  authHeader: string,
  resourceId: string,
  payload: Record<string, unknown>,
): Promise<void> {
  const url = `https://${spaceUrl}/api/fabric/resources/swml_webhooks/${resourceId}`;
  const resp = await fetchWithRetry(url, {
    method: 'PATCH',
    headers: { Authorization: authHeader, 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  if (!resp.ok) {
    throw new ProvisioningError(resp.status, `patch failed: ${await resp.text()}`);
  }
}

async function createResource(
  spaceUrl: string,
  authHeader: string,
  payload: Record<string, unknown>,
): Promise<string> {
  const url = `https://${spaceUrl}/api/fabric/resources/swml_webhooks`;
  const resp = await fetchWithRetry(url, {
    method: 'POST',
    headers: { Authorization: authHeader, 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  if (!resp.ok) {
    throw new ProvisioningError(resp.status, `create failed: ${await resp.text()}`);
  }
  const body = (await resp.json()) as { id: string };
  return body.id;
}

async function ensureResource(
  input: ProvisioningInput,
  name: string,
  primaryRequestUrl: string,
): Promise<ProvisioningResult> {
  const authHeader = basicAuthHeader(input.signalwireProjectId, input.apiToken);
  const list = await listResources(input.spaceUrl, authHeader, name);

  const existing = list.find(
    (r) => r.name === name || r.swml_webhook?.name === name,
  );
  const commonPayload = {
    name,
    primary_request_url: primaryRequestUrl,
    primary_request_method: 'POST',
    username: input.basicAuthUser,
    password: input.basicAuthPassword,
  };

  if (!existing) {
    const id = await createResource(input.spaceUrl, authHeader, commonPayload);
    return { resourceId: id, action: 'created' };
  }
  const currentUrl =
    existing.swml_webhook?.primary_request_url ?? existing.primary_request_url;
  if (currentUrl === primaryRequestUrl) {
    await patchResource(input.spaceUrl, authHeader, existing.id, {
      username: input.basicAuthUser,
      password: input.basicAuthPassword,
    });
    return { resourceId: existing.id, action: 'rotated' };
  }
  await patchResource(input.spaceUrl, authHeader, existing.id, commonPayload);
  return { resourceId: existing.id, action: 'patched' };
}

export function ensureWizardAgent(input: ProvisioningInput): Promise<ProvisioningResult> {
  const url = `${input.appDomain.replace(/\/$/, '')}/swml/wizard-agent`;
  return ensureResource(input, 'wizard-agent', url);
}

export function ensureHireWireAgent(input: ProvisioningInput): Promise<ProvisioningResult> {
  const url = `${input.appDomain.replace(/\/$/, '')}/swml/hirewire-agent`;
  return ensureResource(input, 'hirewire-agent', url);
}
