"use client";

import { useState, useEffect, useRef } from "react";
import {
  Phone,
  PhoneOff,
  Settings,
  Code,
  MessageSquare,
  Zap,
  LogIn,
  User,
} from "lucide-react";
import TranscriptPanel from "@/components/demo-ivr/TranscriptPanel";
import CodeViewer from "@/components/demo-ivr/CodeViewer";
import AdvancedCallControls from "@/components/demo-ivr/AdvancedCallControls";

const EXAMPLE_PROMPTS = [
  "I run a pizza shop. Customers should be able to: 1) Order pizza with size and toppings, 2) Check delivery status by order number, 3) Speak to a manager",
  "I'm a dental office. Callers can: 1) Schedule an appointment, 2) Check appointment status, 3) Ask about services, 4) Talk to the receptionist",
  "I'm a tech support line. Options: 1) Report a bug with severity level, 2) Request a feature, 3) Check ticket status, 4) Escalate to engineer",
];

export default function Page() {
  const [prompt, setPrompt] = useState(EXAMPLE_PROMPTS[0]);
  const [isCallActive, setIsCallActive] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [transcript, setTranscript] = useState([]);
  const [generatedCode, setGeneratedCode] = useState("");
  const [events, setEvents] = useState([]);
  const [callDuration, setCallDuration] = useState(0);
  const [agentEvents, setAgentEvents] = useState([]);
  const [agentAddress, setAgentAddress] = useState(null); // Store the address to dial

  // SignalWire credentials
  const [credentials, setCredentials] = useState({
    spaceUrl: "demo.signalwire.com",
    projectId: "5d30e1ba-32c2-4d62-b94c-4855c2ba739e",
    apiToken: "PTe6d2153a3f9aa2043072c4c51936ba752e94fac0dd15b70f",
  });
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [isConnecting, setIsConnecting] = useState(false);
  const [subscriberData, setSubscriberData] = useState(null);

  const callStartTimeRef = useRef(null);
  const timerIntervalRef = useRef(null);

  // Generate or load persistent subscriber ID
  useEffect(() => {
    if (typeof window !== 'undefined') {
      // Try to load existing subscriberId from localStorage
      let storedSubscriberId = localStorage.getItem('signalwire_subscriber_id');

      // If no subscriber ID exists, generate a new one
      if (!storedSubscriberId) {
        storedSubscriberId = `subscriber_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
        localStorage.setItem('signalwire_subscriber_id', storedSubscriberId);
        console.log('Generated new subscriber ID:', storedSubscriberId);
      } else {
        console.log('Loaded existing subscriber ID:', storedSubscriberId);
      }

      // Store the subscriber ID in state if we have stored subscriber data
      if (subscriberData) {
        setSubscriberData({ ...subscriberData, subscriberId: storedSubscriberId });
      }
    }
  }, []);

  // Update call duration timer
  useEffect(() => {
    if (isCallActive && callStartTimeRef.current) {
      timerIntervalRef.current = setInterval(() => {
        const elapsed = Math.floor(
          (Date.now() - callStartTimeRef.current) / 1000,
        );
        setCallDuration(elapsed);
      }, 1000);
    } else {
      if (timerIntervalRef.current) {
        clearInterval(timerIntervalRef.current);
      }
      setCallDuration(0);
    }

    return () => {
      if (timerIntervalRef.current) {
        clearInterval(timerIntervalRef.current);
      }
    };
  }, [isCallActive]);

  const handleSignalWireLogin = async () => {
    setIsConnecting(true);
    setEvents([]);

    try {
      // Get existing subscriber ID from localStorage
      const storedSubscriberId = localStorage.getItem('signalwire_subscriber_id');

      // Test credentials and create/reuse subscriber
      const response = await fetch("/api/signalwire/connect", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...credentials,
          subscriberId: storedSubscriberId
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to connect to SignalWire");
      }

      const data = await response.json();

      // Store the subscriberId in localStorage (in case it was generated by backend)
      if (data.subscriberId) {
        localStorage.setItem('signalwire_subscriber_id', data.subscriberId);
      }

      setSubscriberData(data);
      setIsLoggedIn(true);

      setEvents([
        {
          type: "system",
          message: `Connected to SignalWire Space: ${credentials.spaceUrl}`,
          timestamp: new Date().toISOString(),
        },
        {
          type: "system",
          message: `Phone number: ${data.phoneNumber || "Not assigned"}`,
          timestamp: new Date().toISOString(),
        },
      ]);

      setIsConnecting(false);
    } catch (error) {
      console.error("Error connecting to SignalWire:", error);
      setEvents([
        {
          type: "error",
          message: error.message,
          timestamp: new Date().toISOString(),
        },
      ]);
      setIsConnecting(false);
    }
  };

  const handleGenerateAndCall = async () => {
    if (!isLoggedIn) {
      setEvents([
        {
          type: "error",
          message: "Please connect to SignalWire first",
          timestamp: new Date().toISOString(),
        },
      ]);
      return;
    }

    setIsGenerating(true);
    setTranscript([]);
    setGeneratedCode("");

    try {
      // Generate agent configuration from prompt
      const response = await fetch("/api/signalwire/generate-agent", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt,
          credentials,
          subscriberId: subscriberData?.subscriberId,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate agent configuration");
      }

      const data = await response.json();
      setGeneratedCode(data.backendConfig?.prompt || prompt); // Show the prompt that was configured
      setAgentAddress(data.callTo); // Store the address to dial (e.g., /subscriber_123/sally-agent)

      // Add events
      setEvents((prev) => [
        ...prev,
        {
          type: "system",
          message: "SWML Agent configuration generated",
          timestamp: new Date().toISOString(),
        },
        {
          type: "system",
          message: `Agent deployed to: ${data.agentUrl}`,
          timestamp: new Date().toISOString(),
        },
        {
          type: "system",
          message: `Call address: ${data.callTo}`,
          timestamp: new Date().toISOString(),
        },
      ]);

      setIsGenerating(false);
    } catch (error) {
      console.error("Error generating agent:", error);
      setEvents((prev) => [
        ...prev,
        {
          type: "error",
          message: error.message,
          timestamp: new Date().toISOString(),
        },
      ]);
      setIsGenerating(false);
    }
  };

  const handleCallStart = () => {
    setIsCallActive(true);
    callStartTimeRef.current = Date.now();
    setTranscript([
      {
        speaker: "system",
        text: "Call connected...",
        timestamp: new Date().toISOString(),
      },
    ]);
    setEvents((prev) => [
      ...prev,
      {
        type: "call",
        message: "Call initiated",
        timestamp: new Date().toISOString(),
      },
    ]);
  };

  const handleCallEnd = () => {
    setIsCallActive(false);
    callStartTimeRef.current = null;
    setTranscript((prev) => [
      ...prev,
      {
        speaker: "system",
        text: "Call ended",
        timestamp: new Date().toISOString(),
      },
    ]);
    setEvents((prev) => [
      ...prev,
      {
        type: "call",
        message: "Call terminated",
        timestamp: new Date().toISOString(),
      },
    ]);
  };

  const handleTranscriptUpdate = (speaker, text) => {
    setTranscript((prev) => [
      ...prev,
      {
        speaker,
        text,
        timestamp: new Date().toISOString(),
      },
    ]);
  };

  const handleEventUpdate = (type, message) => {
    setEvents((prev) => [
      ...prev,
      {
        type,
        message,
        timestamp: new Date().toISOString(),
      },
    ]);
  };

  const handleAgentEvent = (eventData) => {
    setAgentEvents((prev) => [
      ...prev,
      {
        ...eventData,
        timestamp: new Date().toISOString(),
      },
    ]);

    // Handle specific agent events for UI updates
    switch(eventData.type) {
      case 'order_started':
        handleEventUpdate("agent", "Customer started placing an order");
        break;
      case 'item_added':
        handleEventUpdate("agent", `Added ${eventData.item?.name || 'item'} to order`);
        break;
      case 'routing_decision':
        handleEventUpdate("agent", `Routing to ${eventData.department || 'department'}`);
        break;
      case 'agent_thinking':
        handleEventUpdate("agent", `Agent processing: ${eventData.status || 'thinking'}`);
        break;
      default:
        handleEventUpdate("agent", `Agent event: ${eventData.type}`);
    }
  };

  const formatDuration = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800">
      {/* Header */}
      <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-10">
        <div className="max-w-[1800px] mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
                <Zap className="text-white" size={24} />
              </div>
              <div>
                <h1 className="text-xl font-bold text-gray-900 dark:text-white">
                  SignalWire AI IVR Demo
                </h1>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Configure your phone menu with natural language
                </p>
              </div>
            </div>

            <div className="flex items-center space-x-4">
              {isLoggedIn && (
                <div className="flex items-center space-x-2 bg-green-100 dark:bg-green-900/30 px-4 py-2 rounded-full">
                  <User
                    className="text-green-600 dark:text-green-400"
                    size={16}
                  />
                  <span className="text-sm font-medium text-green-700 dark:text-green-300">
                    Connected
                  </span>
                </div>
              )}

              {isCallActive && (
                <div className="flex items-center space-x-2 bg-blue-100 dark:bg-blue-900/30 px-4 py-2 rounded-full">
                  <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse"></div>
                  <span className="text-sm font-medium text-blue-700 dark:text-blue-300">
                    Call Active: {formatDuration(callDuration)}
                  </span>
                </div>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <div className="max-w-[1800px] mx-auto px-6 py-8">
        {/* SignalWire Setup Guide & Login */}
        {!isLoggedIn && (
          <div className="space-y-6 mb-6">
            {/* Setup Guide */}
            <div className="bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-xl border border-blue-200 dark:border-blue-800 p-6">
              <div className="flex items-start space-x-4">
                <div className="flex-shrink-0">
                  <div className="w-12 h-12 bg-blue-500 rounded-lg flex items-center justify-center">
                    <Zap className="text-white" size={24} />
                  </div>
                </div>

                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-blue-900 dark:text-blue-100 mb-2">
                    🚀 Quick Setup Guide
                  </h3>

                  <div className="grid md:grid-cols-3 gap-4 mb-4">
                    <div className="bg-white dark:bg-gray-800/50 rounded-lg p-4 border border-blue-200 dark:border-blue-700">
                      <div className="text-blue-600 dark:text-blue-400 font-semibold text-sm mb-2">
                        Step 1: Get SignalWire Account
                      </div>
                      <p className="text-xs text-gray-600 dark:text-gray-300 mb-2">
                        Sign up at signalwire.com (free trial available)
                      </p>
                      <a
                        href="https://signalwire.com/signup"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center text-xs text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 font-medium"
                      >
                        Sign Up Free →
                      </a>
                    </div>

                    <div className="bg-white dark:bg-gray-800/50 rounded-lg p-4 border border-blue-200 dark:border-blue-700">
                      <div className="text-blue-600 dark:text-blue-400 font-semibold text-sm mb-2">
                        Step 2: Access API Credentials
                      </div>
                      <p className="text-xs text-gray-600 dark:text-gray-300 mb-2">
                        Go to your Space → API → Copy credentials
                      </p>
                      <div className="text-xs text-gray-500 dark:text-gray-400">
                        Space URL, Project ID, API Token
                      </div>
                    </div>

                    <div className="bg-white dark:bg-gray-800/50 rounded-lg p-4 border border-blue-200 dark:border-blue-700">
                      <div className="text-blue-600 dark:text-blue-400 font-semibold text-sm mb-2">
                        Step 3: Connect & Demo
                      </div>
                      <p className="text-xs text-gray-600 dark:text-gray-300 mb-2">
                        Paste credentials below and start building
                      </p>
                      <div className="text-xs text-blue-600 dark:text-blue-400 font-medium">
                        No phone required! ✨
                      </div>
                    </div>
                  </div>

                  <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-3">
                    <div className="flex items-start space-x-2">
                      <div className="text-yellow-600 dark:text-yellow-400 text-xs font-medium">💡 Pro Tip:</div>
                      <div className="text-xs text-yellow-700 dark:text-yellow-300">
                        This demo uses <strong>WebRTC</strong> for browser calling - no phone number setup needed!
                        Just enter your API credentials and click the call button to talk directly to your AI agent.
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Credentials Input */}
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 p-6">
              <div className="flex items-start space-x-4">
                <div className="flex-shrink-0">
                  <div className="w-12 h-12 bg-blue-100 dark:bg-blue-900/30 rounded-lg flex items-center justify-center">
                    <LogIn
                      className="text-blue-600 dark:text-blue-400"
                      size={24}
                    />
                  </div>
                </div>

                <div className="flex-1">
                  <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-4">
                    Enter Your SignalWire API Credentials
                  </label>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                    <div>
                      <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">
                        Space URL
                      </label>
                      <input
                        type="text"
                        value={credentials.spaceUrl}
                        onChange={(e) =>
                          setCredentials((prev) => ({
                            ...prev,
                            spaceUrl: e.target.value,
                          }))
                        }
                        placeholder="your-space.signalwire.com"
                        className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md
                                 bg-white dark:bg-gray-900 text-gray-900 dark:text-white text-sm
                                 focus:border-blue-500 dark:focus:border-blue-400 focus:ring-2 focus:ring-blue-200 dark:focus:ring-blue-800"
                      />
                      <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">
                        Found in Space → Settings
                      </p>
                    </div>

                    <div>
                      <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">
                        Project ID
                      </label>
                      <input
                        type="text"
                        value={credentials.projectId}
                        onChange={(e) =>
                          setCredentials((prev) => ({
                            ...prev,
                            projectId: e.target.value,
                          }))
                        }
                        placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                        className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md
                                 bg-white dark:bg-gray-900 text-gray-900 dark:text-white text-sm
                                 focus:border-blue-500 dark:focus:border-blue-400 focus:ring-2 focus:ring-blue-200 dark:focus:ring-blue-800"
                      />
                      <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">
                        Found in Space → API
                      </p>
                    </div>

                    <div>
                      <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">
                        API Token
                      </label>
                      <input
                        type="password"
                        value={credentials.apiToken}
                        onChange={(e) =>
                          setCredentials((prev) => ({
                            ...prev,
                            apiToken: e.target.value,
                          }))
                        }
                        placeholder="PT..."
                        className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md
                                 bg-white dark:bg-gray-900 text-gray-900 dark:text-white text-sm
                                 focus:border-blue-500 dark:focus:border-blue-400 focus:ring-2 focus:ring-blue-200 dark:focus:ring-blue-800"
                      />
                      <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">
                        Found in Space → API
                      </p>
                    </div>
                  </div>

                  <div className="bg-gray-50 dark:bg-gray-700/50 rounded-lg p-3 mb-4">
                    <div className="text-xs text-gray-600 dark:text-gray-300">
                      <strong>🔒 Security:</strong> Your credentials are only used to connect to your SignalWire space and generate WebRTC tokens.
                      They're never stored permanently and only exist in your browser session.
                    </div>
                  </div>
                </div>

                <div className="flex-shrink-0">
                  <button
                    onClick={handleSignalWireLogin}
                    disabled={
                      isConnecting ||
                      !credentials.spaceUrl ||
                      !credentials.projectId ||
                      !credentials.apiToken
                    }
                    className="h-12 px-6 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700
                             text-white font-semibold rounded-lg shadow-lg
                             disabled:opacity-50 disabled:cursor-not-allowed
                             transition-all duration-150 hover:shadow-xl hover:scale-105 active:scale-95
                             flex items-center space-x-2"
                  >
                    {isConnecting ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                        <span>Connecting...</span>
                      </>
                    ) : (
                      <>
                        <LogIn size={18} />
                        <span>Connect</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Advanced Call Controls */}
        {generatedCode && (
          <div className="mb-6">
            <AdvancedCallControls
              isCallActive={isCallActive}
              onCallStart={handleCallStart}
              onCallEnd={handleCallEnd}
              onTranscriptUpdate={handleTranscriptUpdate}
              onEventUpdate={handleEventUpdate}
              onAgentEvent={handleAgentEvent}
              subscriberData={subscriberData}
              credentials={credentials}
              agentAddress={agentAddress}
            />
          </div>
        )}

        {/* Prompt Input Section - Only show when logged in */}
        {isLoggedIn && (
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 p-6 mb-6">
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0">
                <div className="w-12 h-12 bg-purple-100 dark:bg-purple-900/30 rounded-lg flex items-center justify-center">
                  <Settings
                    className="text-purple-600 dark:text-purple-400"
                    size={24}
                  />
                </div>
              </div>

              <div className="flex-1">
                <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
                  Describe Your IVR Menu
                </label>

                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  disabled={isCallActive}
                  className="w-full h-32 px-4 py-3 border-2 border-gray-300 dark:border-gray-600 rounded-lg
                           bg-white dark:bg-gray-900 text-gray-900 dark:text-white
                           focus:border-blue-500 dark:focus:border-blue-400 focus:ring-2 focus:ring-blue-200 dark:focus:ring-blue-800
                           disabled:opacity-50 disabled:cursor-not-allowed
                           resize-none font-mono text-sm leading-relaxed"
                  placeholder="Describe your phone menu in plain English..."
                />

                <div className="mt-3 flex flex-wrap gap-2">
                  <span className="text-xs font-medium text-gray-500 dark:text-gray-400">
                    Quick examples:
                  </span>
                  {EXAMPLE_PROMPTS.map((example, idx) => (
                    <button
                      key={idx}
                      onClick={() => setPrompt(example)}
                      disabled={isCallActive}
                      className="text-xs px-3 py-1 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600
                               text-gray-700 dark:text-gray-300 rounded-full transition-colors duration-150
                               disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      Example {idx + 1}
                    </button>
                  ))}
                </div>
              </div>

              <div className="flex-shrink-0">
                <button
                  onClick={handleGenerateAndCall}
                  disabled={isGenerating || isCallActive || !prompt.trim()}
                  className="h-12 px-6 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700
                           text-white font-semibold rounded-lg shadow-lg
                           disabled:opacity-50 disabled:cursor-not-allowed
                           transition-all duration-150 hover:shadow-xl hover:scale-105 active:scale-95
                           flex items-center space-x-2"
                >
                  {isGenerating ? (
                    <>
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                      <span>Generating...</span>
                    </>
                  ) : (
                    <>
                      <Zap size={18} />
                      <span>Generate Agent</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Split Panel View */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left Panel: Transcript & Events */}
          <div className="space-y-6">
            <TranscriptPanel transcript={transcript} isActive={isCallActive} />

            {/* System Events Panel */}
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden">
              <div className="bg-gradient-to-r from-green-500 to-emerald-600 px-4 py-3">
                <div className="flex items-center space-x-2">
                  <Zap className="text-white" size={18} />
                  <h3 className="text-sm font-semibold text-white">
                    System Events
                  </h3>
                </div>
              </div>

              <div className="p-4 max-h-64 overflow-y-auto">
                {events.length === 0 ? (
                  <div className="text-center py-8 text-gray-400 dark:text-gray-500 text-sm">
                    No events yet. Generate an agent to begin.
                  </div>
                ) : (
                  <div className="space-y-2">
                    {events.map((event, idx) => (
                      <div
                        key={idx}
                        className={`flex items-start space-x-2 p-2 rounded-lg text-xs ${
                          event.type === "error"
                            ? "bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-300"
                            : event.type === "call"
                              ? "bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300"
                              : event.type === "agent"
                                ? "bg-purple-50 dark:bg-purple-900/20 text-purple-700 dark:text-purple-300"
                                : "bg-gray-50 dark:bg-gray-700/50 text-gray-700 dark:text-gray-300"
                        }`}
                      >
                        <span className="font-mono opacity-50">
                          {new Date(event.timestamp).toLocaleTimeString()}
                        </span>
                        <span className="font-medium">{event.message}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Agent Events Panel */}
            {agentEvents.length > 0 && (
              <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden">
                <div className="bg-gradient-to-r from-purple-500 to-pink-600 px-4 py-3">
                  <div className="flex items-center space-x-2">
                    <MessageSquare className="text-white" size={18} />
                    <h3 className="text-sm font-semibold text-white">
                      Real-Time Agent Events
                    </h3>
                    <div className="bg-white/20 px-2 py-0.5 rounded-full">
                      <span className="text-xs font-medium text-white">
                        {agentEvents.length}
                      </span>
                    </div>
                  </div>
                </div>

                <div className="p-4 max-h-64 overflow-y-auto">
                  <div className="space-y-3">
                    {agentEvents.slice(-10).map((event, idx) => (
                      <div key={idx} className="bg-purple-50 dark:bg-purple-900/20 rounded-lg p-3">
                        <div className="flex items-start justify-between mb-1">
                          <span className="text-sm font-semibold text-purple-700 dark:text-purple-300">
                            {event.type}
                          </span>
                          <span className="text-xs text-purple-500 dark:text-purple-400 font-mono">
                            {new Date(event.timestamp).toLocaleTimeString()}
                          </span>
                        </div>
                        {event.status && (
                          <div className="text-xs text-purple-600 dark:text-purple-400 mb-1">
                            Status: {event.status}
                          </div>
                        )}
                        {event.department && (
                          <div className="text-xs text-purple-600 dark:text-purple-400 mb-1">
                            Department: {event.department}
                          </div>
                        )}
                        {event.item && (
                          <div className="text-xs text-purple-600 dark:text-purple-400">
                            Item: {event.item.name} (${event.item.price})
                          </div>
                        )}
                        {event.message && (
                          <div className="text-xs text-gray-600 dark:text-gray-400 mt-1">
                            {event.message}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Right Panel: Generated Code */}
          <div>
            <CodeViewer code={generatedCode} isGenerating={isGenerating} />
          </div>
        </div>
      </div>
    </div>
  );
}
